######################################################################
# Automatically generated by qmake (2.01a) S�b 6. Jun 20:49:06 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . qtc-gdbmacros utils
INCLUDEPATH += .
CONFIG += console

# Input
HEADERS += Image.h \
           ImageAlternative.h \
           Kmeans.h \
           MainWindow.h \
           Segmentation.h \
           utils/Array.h \
           utils/Matrix.h \
           utils/require.h \
           utils/utils.h
FORMS += MainWindow.ui
SOURCES += Image.cpp \
           ImageAlternative.cpp \
           Kmeans.cpp \
           main.cpp \
           MainWindow.cpp \
           Segmentation.cpp \
           qtc-gdbmacros/gdbmacros.cpp
